APP = (
    "Trading CLI Bot for local exchange account checks and capped trade smoke tests.\n\n"
    "Run without a command to show wallet summary. Credentials are read from .env by default and are never printed.\n\n"
    "Common commands:\n"
    "  tbot\n"
    "  tbot summary\n"
    "  tbot balance binance spot\n"
    "  tbot snapshot\n"
    "  tbot daemon start\n"
    "  tbot daemon status\n"
    "  tbot positions okx\n"
    "  tbot transfer okx USDT 10 spot perp\n"
    "  tbot pair-plan binance okx SOL/USDT 20\n"
    "  tbot pair-run okx gate SOL/USDT 20 --confirm \"LIVE_PAIR_OPEN:okx:gate:SOLUSDT:QUOTE_20\"\n"
    "  tbot pair-close-plan okx gate SOL/USDT\n"
    "  tbot pair-close-run okx gate SOL/USDT --confirm \"LIVE_PAIR_CLOSE:okx:gate:SOLUSDT\"\n"
    "  tbot pair-status aspair_xxx\n"
    "  tbot pair-resume aspair_xxx --confirm \"LIVE_PAIR_OPEN:okx:gate:SOLUSDT:QUOTE_20\"\n"
    "  tbot plan okx perp open-short BTC/USDT 80 --bbo\n"
    "  tbot run gate perp close-short BTC/USDT --bbo --confirm \"LIVE_GATE_PERP_CLOSE_SHORT:BTCUSDT:ALL\"\n"
    "  tbot trade smoke --help"
)
WALLET = "Wallet commands moved to top-level commands."
TRADE = "Plan or execute capped trade smoke tests."
CAPABILITIES = "Show static CCXT and adapter capability flags; no private API call is made."
SUMMARY = "Fast USDT wallet overview for binance/okx/gate/mexc."
SNAPSHOT = "Full account snapshot: all spot assets plus all active perp positions without symbol-by-symbol scans."
BALANCE = "Read one exchange wallet using the normalized account schema by default; use --raw for debug exchange payloads."
POSITIONS = "Dump redacted perp positions for one exchange; omit symbol to ask CCXT for all positions."
ORDERS = "Dump redacted open orders for one exchange, market, and symbol."
TRANSFER = "Plan or execute an account-internal transfer. Live mode requires the exact confirmation phrase."
TOP_BALANCE = "Read one exchange wallet. Example: tbot balance binance spot"
TOP_POSITIONS = "Read one exchange perp positions. Example: tbot positions okx"
TOP_ORDERS = "Read open orders. Example: tbot orders binance spot BTC/USDT"
TOP_TRANSFER = "Plan or execute an internal transfer. Example: tbot transfer okx USDT 10 spot perp"
WEB = "Start the localhost Trading Gateway web dashboard."
DAEMON = "Manage the localhost Trading Gateway live daemon required for live trading paths."
LAB_PLAN = "Preview a single-leg spot/perp intent across binance/okx/gate/mexc with live exchange minimums."
LAB_RUN = "Execute a real single-leg order with closed-loop verification. Perp close-long/close-short without quote uses a position-cleanup close-all mode."
PAIR_PLAN = "Preview a multi-exchange spot-long + perp-short pair with one shared base quantity."
PAIR_RUN = "Execute a real multi-exchange spot-long + perp-short pair with closed-loop verification. This remains a dual-leg convergence flow, not single-leg cleanup mode."
PAIR_CLOSE_PLAN = "Preview a pair close workflow that sells spot and buys back perp short toward flat exposure."
PAIR_CLOSE_RUN = "Execute a real pair close workflow with closed-loop verification and residual cleanup."
PAIR_STATUS = "Restore a pair run from its local journal and query live order/balance state."
PAIR_RESUME = "Resume a pair run from journal state. The original confirmation phrase is still required."
BINANCE = "Removed."
BINANCE_CHECK = "Removed."
PLAN = "Build an order plan and print the live confirmation phrase; never places an order."
SMOKE = "Run a capped order smoke test. Live quote amount is capped at 10 USDT."
